name=makeduinoDCMotor
version=1.2.0
author=Oscar Sanchis
maintainer=Oscar Sanchis
sentence=Control simple de dos motors DC amb makeduino per Arduino UNO R4 Minima.
paragraph=Permet controlar direccio, velocitat (-100 a 100) i temps de funcionament de dos motors DC amb Arduino UNO R4 Minima. M1 usa els pins 10 i 12; M2 usa els pins 11 i 13.
category=Device Control
url=https://github.com/MakeAndLearn/makeduinoDCMotor
architectures=*
